# Generated by Django 4.2.1 on 2024-05-25 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='item_name',
        ),
        migrations.AddField(
            model_name='basket',
            name='item',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='orders.item'),
            preserve_default=False,
        ),
    ]
