# Generated by Django 4.2.1 on 2024-05-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
