# Generated by Django 4.2.1 on 2024-05-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
    ]
