# Generated by Django 4.2.1 on 2024-05-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_basket_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
        migrations.AddField(
            model_name='item',
            name='isAvailable',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
