# Generated by Django 4.2.1 on 2024-05-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_basket_quantity_guestbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='GuestBasket',
        ),
    ]
