# Generated by Django 4.2.1 on 2024-08-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_basket_session_id_alter_basket_user_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='option',
        ),
    ]
