# Generated by Django 4.2.1 on 2024-08-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_options_remove_item_options_delete_option_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
