# Generated by Django 4.2.1 on 2024-08-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_basket_created_at_basket_option_basket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hasOption',
            field=models.BooleanField(default=0),
        ),
    ]
