# Generated by Django 4.2.1 on 2024-08-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_item_hasoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hasOption',
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
